# Generated by Django 3.1.2 on 2022-05-12 03:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='Apellidos')),
                ('edad', models.IntegerField(null=True)),
                ('date_joined', models.DateTimeField(null=True, verbose_name='Fecha de alta')),
                ('especialidad', models.CharField(choices=[('MF', 'Medico de Familia'), ('DG', 'Digestivo'), ('NE', 'Neurologo'), ('DT', 'Dermatologo'), ('TR', 'Traumatologo'), ('SE', 'Sin Especialidad')], default='SE', max_length=2)),
                ('username', models.CharField(max_length=30, null=True, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=30, null=True, verbose_name='Contraseña')),
                ('is_active', models.SmallIntegerField(null=True, verbose_name='Activo')),
                ('is_paciente', models.BooleanField(null=True, verbose_name='paciente status')),
                ('is_medico', models.BooleanField(null=True, verbose_name='medico status')),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('foto', models.ImageField(null=True, upload_to='fotos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('precio', models.FloatField(null=True)),
                ('idPaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('descripcion', models.TextField(max_length=100, null=True)),
                ('receta', models.CharField(max_length=1, null=True)),
                ('precio', models.FloatField(null=True)),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra_medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCompra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.compra')),
                ('idMedicamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nucleo.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(null=True)),
                ('observaciones', models.TextField(max_length=200, null=True)),
                ('idMedico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
                ('idPaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
