# Generated by Django 3.1.2 on 2022-05-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.SmallIntegerField(default=1, verbose_name='Activo'),
            preserve_default=False,
        ),
    ]
