# Generated by Django 3.1.2 on 2022-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_auto_20220601_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='Contraseña'),
        ),
    ]
