# Generated by Django 3.1.2 on 2022-06-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_auto_20220601_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
