# Generated by Django 3.1.2 on 2022-06-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0006_auto_20220615_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateField(null=True, verbose_name='Fecha de alta'),
        ),
    ]
