# Generated by Django 3.1.2 on 2022-06-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0007_auto_20220615_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(null=True, verbose_name='Fecha de alta'),
        ),
    ]
