# Generated by Django 3.1.2 on 2022-06-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0008_auto_20220615_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra_medicamento',
            name='cant',
            field=models.IntegerField(null=True),
        ),
    ]
